package com.subsnag.api

import android.util.Log
import com.subsnag.model.SubtitleTrack
import com.subsnag.model.VideoInfo
import io.ktor.client.*
import io.ktor.client.engine.android.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import kotlinx.serialization.json.*
import org.jsoup.Jsoup
import java.net.URLDecoder

class YouTubeApi {
    private val client = HttpClient(Android) {
        engine {
            connectTimeout = 30_000
            socketTimeout = 30_000
        }
    }

    private val json = Json {
        ignoreUnknownKeys = true
        isLenient = true
    }

    companion object {
        private const val TAG = "YouTubeApi"
    }

    /**
     * Fetches video information including title, thumbnail, and available caption tracks.
     */
    suspend fun getVideoInfo(videoId: String): Result<VideoInfo> {
        return try {
            Log.d(TAG, "Fetching video info for: $videoId")

            // Step 1: Get basic info from oEmbed API
            val oEmbedUrl = "https://www.youtube.com/oembed?url=https://youtube.com/watch?v=$videoId&format=json"
            Log.d(TAG, "Fetching oEmbed: $oEmbedUrl")
            val oEmbedResponse = client.get(oEmbedUrl).bodyAsText()
            val oEmbedJson = json.parseToJsonElement(oEmbedResponse).jsonObject

            val title = oEmbedJson["title"]?.jsonPrimitive?.content ?: "Unknown Title"
            val thumbnailUrl = oEmbedJson["thumbnail_url"]?.jsonPrimitive?.content
                ?: "https://i.ytimg.com/vi/$videoId/hqdefault.jpg"

            Log.d(TAG, "Video title: $title")

            // Step 2: Fetch the watch page to get caption tracks
            val watchPageUrl = "https://www.youtube.com/watch?v=$videoId"
            Log.d(TAG, "Fetching watch page: $watchPageUrl")
            val watchPageHtml = client.get(watchPageUrl).bodyAsText()

            val captionTracks = extractCaptionTracks(watchPageHtml)
            Log.d(TAG, "Found ${captionTracks.size} caption tracks")

            if (captionTracks.isEmpty()) {
                Log.w(TAG, "No subtitles available")
                return Result.failure(Exception("No subtitles available for this video"))
            }

            Result.success(
                VideoInfo(
                    videoId = videoId,
                    title = title,
                    thumbnailUrl = thumbnailUrl,
                    availableTracks = captionTracks
                )
            )
        } catch (e: Exception) {
            Log.e(TAG, "Failed to fetch video info", e)
            Result.failure(Exception("Failed to fetch video info: ${e.message}", e))
        }
    }

    /**
     * Extracts caption track information from the YouTube watch page HTML.
     */
    private fun extractCaptionTracks(html: String): List<SubtitleTrack> {
        val tracks = mutableListOf<SubtitleTrack>()

        try {
            // Look for ytInitialPlayerResponse in the HTML
            val playerResponsePattern = Regex(""""captionTracks":\[(.*?)\]""")
            val matchResult = playerResponsePattern.find(html)

            if (matchResult != null) {
                val captionTracksJson = "[${matchResult.groupValues[1]}]"
                val tracksArray = json.parseToJsonElement(captionTracksJson).jsonArray

                for (trackElement in tracksArray) {
                    val trackObj = trackElement.jsonObject
                    val baseUrl = trackObj["baseUrl"]?.jsonPrimitive?.content ?: continue
                    val languageCode = trackObj["languageCode"]?.jsonPrimitive?.content ?: "en"

                    val name = trackObj["name"]?.jsonObject?.get("simpleText")?.jsonPrimitive?.content
                        ?: trackObj["name"]?.jsonObject?.get("runs")?.jsonArray?.get(0)?.jsonObject?.get("text")?.jsonPrimitive?.content
                        ?: languageCode

                    val isAutoGenerated = trackObj["kind"]?.jsonPrimitive?.content == "asr"

                    tracks.add(
                        SubtitleTrack(
                            languageCode = languageCode,
                            languageName = name,
                            isAutoGenerated = isAutoGenerated,
                            baseUrl = baseUrl
                        )
                    )
                }
            }

            // Fallback: try alternative pattern
            if (tracks.isEmpty()) {
                val altPattern = Regex("""var ytInitialPlayerResponse = (\{.*?\});""")
                val altMatch = altPattern.find(html)
                if (altMatch != null) {
                    val playerResponse = json.parseToJsonElement(altMatch.groupValues[1]).jsonObject
                    val captions = playerResponse["captions"]?.jsonObject
                    val playerCaptionRenderer = captions?.get("playerCaptionsTracklistRenderer")?.jsonObject
                    val captionTracks = playerCaptionRenderer?.get("captionTracks")?.jsonArray

                    captionTracks?.forEach { trackElement ->
                        val trackObj = trackElement.jsonObject
                        val baseUrl = trackObj["baseUrl"]?.jsonPrimitive?.content ?: return@forEach
                        val languageCode = trackObj["languageCode"]?.jsonPrimitive?.content ?: "en"
                        val name = trackObj["name"]?.jsonObject?.get("simpleText")?.jsonPrimitive?.content ?: languageCode
                        val isAutoGenerated = trackObj["kind"]?.jsonPrimitive?.content == "asr"

                        tracks.add(
                            SubtitleTrack(
                                languageCode = languageCode,
                                languageName = name,
                                isAutoGenerated = isAutoGenerated,
                                baseUrl = baseUrl
                            )
                        )
                    }
                }
            }
        } catch (e: Exception) {
            // If parsing fails, try the timedtext API as a last resort
            // This will be handled in getSubtitles
        }

        return tracks
    }

    /**
     * Fetches subtitle content in SRT format.
     */
    suspend fun getSubtitles(videoId: String, track: SubtitleTrack): Result<String> {
        return try {
            val subtitleUrl = if (track.baseUrl != null) {
                // Use the baseUrl from the track info
                track.baseUrl
            } else {
                // Fallback to timedtext API
                "https://www.youtube.com/api/timedtext?v=$videoId&lang=${track.languageCode}&fmt=srv3"
            }

            Log.d(TAG, "Fetching subtitles from: $subtitleUrl")
            val response = client.get(subtitleUrl).bodyAsText()
            Log.d(TAG, "Subtitle response length: ${response.length} bytes")
            Log.d(TAG, "Response preview: ${response.take(200)}")

            if (response.isBlank()) {
                Log.e(TAG, "Empty subtitle response")
                return Result.failure(Exception("Empty subtitle response from YouTube"))
            }

            // Detect format and convert to SRT
            val srtContent = when {
                response.trim().startsWith("<?xml") || response.trim().startsWith("<transcript") -> {
                    Log.d(TAG, "Detected XML format")
                    convertXMLToSRT(response)
                }
                response.trim().startsWith("{") -> {
                    Log.d(TAG, "Detected JSON format")
                    convertToSRT(response)
                }
                else -> {
                    Log.w(TAG, "Unknown format, trying XML parser")
                    convertXMLToSRT(response)
                }
            }

            Log.d(TAG, "Converted SRT length: ${srtContent.length} bytes")
            if (srtContent.isBlank()) {
                Log.e(TAG, "Conversion resulted in empty SRT")
                return Result.failure(Exception("Failed to convert subtitles to SRT format"))
            }

            Result.success(srtContent)
        } catch (e: Exception) {
            Log.e(TAG, "Failed to fetch subtitles", e)
            Result.failure(Exception("Failed to fetch subtitles: ${e.message}", e))
        }
    }

    /**
     * Converts YouTube's JSON3 subtitle format to SRT.
     */
    private fun convertToSRT(jsonContent: String): String {
        val srtBuilder = StringBuilder()
        var counter = 1

        try {
            val jsonObject = json.parseToJsonElement(jsonContent).jsonObject
            val events = jsonObject["events"]?.jsonArray ?: return ""

            for (event in events) {
                val eventObj = event.jsonObject
                val startTime = eventObj["tStartMs"]?.jsonPrimitive?.long ?: continue
                val duration = eventObj["dDurationMs"]?.jsonPrimitive?.long ?: continue
                val segs = eventObj["segs"]?.jsonArray

                if (segs != null && segs.isNotEmpty()) {
                    val text = segs.joinToString("") { seg ->
                        seg.jsonObject["utf8"]?.jsonPrimitive?.content ?: ""
                    }.trim()

                    if (text.isNotEmpty()) {
                        val endTime = startTime + duration
                        srtBuilder.append("$counter\n")
                        srtBuilder.append("${formatTime(startTime)} --> ${formatTime(endTime)}\n")
                        srtBuilder.append("$text\n\n")
                        counter++
                    }
                }
            }
        } catch (e: Exception) {
            // If JSON parsing fails, try XML format
            return convertXMLToSRT(jsonContent)
        }

        return srtBuilder.toString()
    }

    /**
     * Converts YouTube's SRV3 (XML) subtitle format to SRT.
     */
    private fun convertSRV3ToSRT(xmlContent: String): String {
        return convertXMLToSRT(xmlContent)
    }

    /**
     * Converts XML subtitle format to SRT.
     */
    private fun convertXMLToSRT(xmlContent: String): String {
        val srtBuilder = StringBuilder()
        var counter = 1

        try {
            Log.d(TAG, "Parsing XML content...")
            val doc = Jsoup.parse(xmlContent, "", org.jsoup.parser.Parser.xmlParser())
            val textElements = doc.select("text")
            Log.d(TAG, "Found ${textElements.size} text elements")

            if (textElements.isEmpty()) {
                Log.w(TAG, "No <text> elements found in XML")
            }

            for (element in textElements) {
                val startStr = element.attr("start")
                val durStr = element.attr("dur")
                val rawText = element.text()

                Log.v(TAG, "Element $counter: start=$startStr, dur=$durStr, text=${rawText.take(50)}")

                val start = startStr.toDoubleOrNull()?.times(1000)?.toLong()
                if (start == null) {
                    Log.w(TAG, "Invalid start time: $startStr")
                    continue
                }

                val duration = durStr.toDoubleOrNull()?.times(1000)?.toLong() ?: 3000

                // Use Jsoup's built-in HTML entity decoding
                val text = Jsoup.parse(rawText).text().trim()

                if (text.isNotEmpty()) {
                    val end = start + duration
                    srtBuilder.append("$counter\n")
                    srtBuilder.append("${formatTime(start)} --> ${formatTime(end)}\n")
                    srtBuilder.append("$text\n\n")
                    counter++
                }
            }

            Log.d(TAG, "Converted ${counter - 1} subtitle entries")
        } catch (e: Exception) {
            Log.e(TAG, "Failed to parse XML", e)
            throw Exception("Failed to parse subtitle XML: ${e.message}")
        }

        return srtBuilder.toString()
    }

    /**
     * Formats milliseconds to SRT timestamp format (HH:MM:SS,mmm).
     */
    private fun formatTime(milliseconds: Long): String {
        val hours = milliseconds / 3600000
        val minutes = (milliseconds % 3600000) / 60000
        val seconds = (milliseconds % 60000) / 1000
        val millis = milliseconds % 1000

        return String.format("%02d:%02d:%02d,%03d", hours, minutes, seconds, millis)
    }

    /**
     * Decodes HTML entities.
     */
    private fun decodeHtml(text: String): String {
        return text
            .replace("&amp;", "&")
            .replace("&lt;", "<")
            .replace("&gt;", ">")
            .replace("&quot;", "\"")
            .replace("&#39;", "'")
            .replace("&apos;", "'")
    }

    fun close() {
        client.close()
    }
}
