package com.subsnag.model

import kotlinx.serialization.Serializable

@Serializable
data class VideoInfo(
    val videoId: String,
    val title: String,
    val thumbnailUrl: String,
    val availableTracks: List<SubtitleTrack>
)

@Serializable
data class SubtitleTrack(
    val languageCode: String,
    val languageName: String,
    val isAutoGenerated: Boolean,
    val baseUrl: String? = null
) {
    val displayName: String
        get() = if (isAutoGenerated) {
            "$languageName (auto-generated)"
        } else {
            languageName
        }
}
